// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fislyheqbyrhcrzasetl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpc2x5aGVxYnlyaGNyemFzZXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjE0OTEsImV4cCI6MjA2NTUzNzQ5MX0.FwKfrRqPu46yX34tAD4O8srbWxDVCNm0rlGSWyT_c3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);